import type { Stock, StockAnalysis } from '../types/stock';

export const mockStocks: Stock[] = [
  { id: 1, ticker: 'INVE-A.ST', name: 'Investor A', exchange: 'Stockholm', isActive: true, sortOrder: 1 },
  { id: 2, ticker: 'GOOG', name: 'Alphabet Inc Class C', exchange: 'US', isActive: true, sortOrder: 2 },
  { id: 3, ticker: 'MSFT', name: 'Microsoft', exchange: 'US', isActive: true, sortOrder: 3 },
  { id: 4, ticker: 'TSM', name: 'Taiwan Semiconductor Mfg Co', exchange: 'US', isActive: true, sortOrder: 4 },
  { id: 6, ticker: 'ASML', name: 'ASML HOLDING', exchange: 'Netherlands', isActive: true, sortOrder: 6 },
  { id: 7, ticker: 'NVDA', name: 'NVIDIA', exchange: 'US', isActive: true, sortOrder: 7 },
  { id: 9, ticker: 'AMD', name: 'Advanced Micro Devices', exchange: 'US', isActive: true, sortOrder: 9 },
  { id: 10, ticker: 'AMZN', name: 'Amazon.com', exchange: 'US', isActive: false, sortOrder: 10 },
];

export const mockAnalyses: StockAnalysis[] = [
  {
    id: 101,
    stockId: 7,
    ticker: 'NVDA',
    companyName: 'NVIDIA',
    impactScore: 92,
    confidenceScore: 86,
    expectedMove: 38,
    direction: 'positive',
    summary: 'Recent AI accelerator demand and data center headlines point to strong near-term narrative momentum, with the provided news context supporting a high-impact positive read.',
    opportunities: ['AI infrastructure demand remains a core catalyst', 'High analyst attention may amplify momentum'],
    risks: ['Valuation sensitivity remains high', 'Any supply or margin pressure could reverse sentiment'],
    usedNewsCount: 10,
    analyzedAt: '2026-05-07T09:18:00Z',
  },
  {
    id: 102,
    stockId: 3,
    ticker: 'MSFT',
    companyName: 'Microsoft',
    impactScore: 78,
    confidenceScore: 81,
    expectedMove: 24,
    direction: 'positive',
    summary: 'The news set highlights cloud and AI platform strength. The likely impact is positive, though less explosive than chip-led names.',
    opportunities: ['AI monetization across enterprise products', 'Cloud growth remains a durable signal'],
    risks: ['Regulatory and capex scrutiny can weigh on multiples'],
    usedNewsCount: 9,
    analyzedAt: '2026-05-07T08:52:00Z',
  },
  {
    id: 103,
    stockId: 2,
    ticker: 'GOOG',
    companyName: 'Alphabet Inc Class C',
    impactScore: 64,
    confidenceScore: 72,
    expectedMove: 8,
    direction: 'mixed',
    summary: 'Provided headlines are constructive on AI product velocity but mixed around competitive pressure and regulatory noise.',
    opportunities: ['Search and cloud AI features can support revenue quality'],
    risks: ['Regulatory headlines may cap sentiment', 'AI competition remains visible'],
    usedNewsCount: 8,
    analyzedAt: '2026-05-06T17:25:00Z',
  },
  {
    id: 104,
    stockId: 9,
    ticker: 'AMD',
    companyName: 'Advanced Micro Devices',
    impactScore: 70,
    confidenceScore: 68,
    expectedMove: 16,
    direction: 'positive',
    summary: 'News context suggests improving AI chip positioning, but confidence is moderate because the supplied items are not uniformly specific.',
    opportunities: ['AI accelerator market share optionality', 'Server CPU demand can support broader story'],
    risks: ['Execution risk versus larger competitors', 'Guidance sensitivity'],
    usedNewsCount: 7,
    analyzedAt: '2026-05-06T14:04:00Z',
  },
  {
    id: 105,
    stockId: 6,
    ticker: 'ASML',
    companyName: 'ASML HOLDING',
    impactScore: 58,
    confidenceScore: 64,
    expectedMove: -6,
    direction: 'neutral',
    summary: 'The context is important but not decisively directional. Export and cycle concerns offset long-term semiconductor equipment demand.',
    opportunities: ['Structural lithography demand remains relevant'],
    risks: ['Export restrictions and order timing can pressure sentiment'],
    usedNewsCount: 6,
    analyzedAt: '2026-05-05T18:30:00Z',
  },
];

