// <auto-generated />
using System;
using AlphaMind.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlphaMind.Api.Migrations
{
    [DbContext(typeof(AlphaMindDbContext))]
    partial class AlphaMindDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlphaMind.Api.Entities.FetcherRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DuplicatesSkipped")
                        .HasColumnType("int");

                    b.Property<int>("ErrorsCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("NewNewsSaved")
                        .HasColumnType("int");

                    b.Property<int>("NewsFetched")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StocksChecked")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FetcherRuns");
                });

            modelBuilder.Entity("AlphaMind.Api.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "Stockholm",
                            IsActive = true,
                            Name = "Investor A",
                            SortOrder = 1,
                            Ticker = "INVE-A.ST"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "US",
                            IsActive = true,
                            Name = "Alphabet Inc Class C",
                            SortOrder = 2,
                            Ticker = "GOOG"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "US",
                            IsActive = true,
                            Name = "Microsoft",
                            SortOrder = 3,
                            Ticker = "MSFT"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "US",
                            IsActive = true,
                            Name = "Taiwan Semiconductor Mfg Co",
                            SortOrder = 4,
                            Ticker = "TSM"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "Stockholm",
                            IsActive = true,
                            Name = "Industrivärden C",
                            SortOrder = 5,
                            Ticker = "INDU-C.ST"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "Netherlands",
                            IsActive = true,
                            Name = "ASML HOLDING",
                            SortOrder = 6,
                            Ticker = "ASML"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "US",
                            IsActive = true,
                            Name = "NVIDIA",
                            SortOrder = 7,
                            Ticker = "NVDA"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "Stockholm",
                            IsActive = true,
                            Name = "Svolder B",
                            SortOrder = 8,
                            Ticker = "SVOL-B.ST"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "US",
                            IsActive = true,
                            Name = "Advanced Micro Devices",
                            SortOrder = 9,
                            Ticker = "AMD"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "US",
                            IsActive = true,
                            Name = "Amazon.com",
                            SortOrder = 10,
                            Ticker = "AMZN"
                        });
                });

            modelBuilder.Entity("AlphaMind.Api.Entities.StockAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ExpectedMove")
                        .HasColumnType("int");

                    b.Property<int>("ImpactScore")
                        .HasColumnType("int");

                    b.Property<string>("OpportunitiesJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RisksJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("UsedNewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedAt");

                    b.HasIndex("ImpactScore");

                    b.HasIndex("StockId");

                    b.ToTable("StockAnalyses");
                });

            modelBuilder.Entity("AlphaMind.Api.Entities.StockNews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("StockId");

                    b.HasIndex("ExternalId", "Source")
                        .IsUnique();

                    b.ToTable("StockNews");
                });

            modelBuilder.Entity("AlphaMind.Api.Entities.StockAnalysis", b =>
                {
                    b.HasOne("AlphaMind.Api.Entities.Stock", "Stock")
                        .WithMany("Analyses")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("AlphaMind.Api.Entities.StockNews", b =>
                {
                    b.HasOne("AlphaMind.Api.Entities.Stock", "Stock")
                        .WithMany("NewsItems")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("AlphaMind.Api.Entities.Stock", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("NewsItems");
                });
#pragma warning restore 612, 618
        }
    }
}
